# Generated by Django 2.2.3 on 2021-11-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMERA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('fecha_subida', models.DateField()),
                ('etiquetas', models.TextField()),
                ('tipo', models.TextField()),
                ('identificador', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='curso',
        ),
    ]
