# Generated by Django 2.2.3 on 2021-11-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMERA', '0002_auto_20211117_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='identificador',
        ),
    ]
