# Generated by Django 2.2.3 on 2021-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMERA', '0003_remove_material_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fecha_subida',
            field=models.TextField(),
        ),
    ]
