# Generated by Django 2.2.3 on 2021-11-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMERA', '0005_auto_20211117_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
