# Generated by Django 2.2.3 on 2021-12-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRIMERA', '0009_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='calificacion',
        ),
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='PRIMERA.material')),
            ],
        ),
    ]
